### PR TITLE
Store original image downsample in LabeledImageServer

### PR DESCRIPTION
**Pull request by alanocallaghan**
Continuation of changes discussed in #25 

Previously all labeledservers had downsample of 1, meaning they effectively lost any concept of the original image's resolution. This lead to an inconvenient API for the most common use cases (matched use of similar labelled and original images).

This means that running

```python
ls = LabeledImageServer(original_server.metadata, features, downsample=2)
ls.read_region(downsample=1)
```

will now return an image of the size of `original_server`, rather than downsampled by 2.

It also seems to mean that region requests are resized to the labeledserver's downsampled coordinate space, without needing to run `region.downsample_region()` on every request.

### CODE REVIEW

**Comment by alanocallaghan** [comment]
Worth checking the tests I changed/added :)

**Review by Rylern — APPROVED** [review]
I think it would be great if you could add a comment regarding how the new downsample behaviour works (in the docstring of the `LabeledImageServer` class or in its constructor). Just something to say the `LabeledImageServer` has the same size as the original server and level 0 can have a downsample > 1

**Comment by alanocallaghan** [comment]
Great point, thanks! I will also make this clear in the notebooks before merging

**Comment by alanocallaghan** [comment]
Can you have a quick look over the comment/s and see if it's clear?

**Review by Rylern — APPROVED** [review]
It's clear, thanks

**Pull request merged**
